baseURL = 'https://thetoddluc.io/'
languageCode = 'en-us'
title = 'TheToddLuci0'
theme = 'ficurinia'

copyright = "TheToddLuci0"

[params]
author = 'TheToddLuci0'
logo = '/logo.png'
enableShareOnFediverse = true
fediverseAccount = "@TheToddLuci0@infosec.exchange"

[menu]
[[menu.icons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/TheToddLuci0"
    weight = 10
[[menu.icons]]
    identifier = "mastodon"
    name = "Mastodon"
    url = "https://infosec.exchange/@TheToddLuci0"
[[menu.icons]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/TheToddLuci0"

[outputs]
    home = ["HTML", "JSON"]

# Needed for GH Pages
# https://gohugo.io/host-and-deploy/host-on-github-pages/#step-5
[caches]
  [caches.images]
    dir = ':cacheDir/images'